### ISSUE TITLE
Zextras login theme are broken in Zimbra 9

### ISSUE THREAD

**Issue by RasyiidWho** [ZeXtras/zextras-theme#1]
Just want to report that theme layout didn't show correctly on Zimbra 9 (9.0.0_GA_3990.FOSS)

I have already followed step, even using compiled version (.deb)

![image](https://user-images.githubusercontent.com/19422415/104134514-a6a94400-53bc-11eb-943d-865cabc38e44.png)

**Comment by M0Rf30** [comment]
Greetings @RasyiidWho and thanks for your report. 
This issue will be moved on our official help desk, in order to be processed.

If you have further requests or comments feel free to open a ticket using [our support platform](https://support.zextras.com/hc/en-us)

Thanks for your contribution.
Best regards
